name: simple-cprov
version: 1.01
summary: This is a test snap
description: |
  This is a test snap ...
confinement: strict
grade: stable

apps:
    simple:
        command: bin/simple

parts:
    simple:
        plugin: make
        source: .
